/* eslint-disable */

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const MINE_IMAGE_WITH_URL_REQUEST = 'MINE_IMAGE_WITH_URL_REQUEST';
export const MINE_IMAGE_WITH_URL_SUCCESS = 'MINE_IMAGE_WITH_URL_SUCCESS';
export const MINE_IMAGE_WITH_URL_FAIL = 'MINE_IMAGE_WITH_URL_FAIL';

export const NEWS_SUBSCRIPTION_REQUEST = 'NEWS_SUBSCRIPTION_REQUEST';
export const NEWS_SUBSCRIPTION_SUCCESS = 'NEWS_SUBSCRIPTION_SUCCESS';
export const NEWS_SUBSCRIPTION_FAIL = 'NEWS_SUBSCRIPTION_FAIL';
